name: update
on:
  schedule:
    - cron: '30 3/12 * * *' #每日更新
  watch:
    types: [started]
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  rss-make:
    runs-on: ubuntu-latest #运行环境
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Git set'
        run: |
             git init
             git pull
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7 #v3
      - name: 'Install requirements'
        run: |
             pip install wget
             pip install bs4
             pip install urllib3 #安装依赖permissions:
      - name: 'Working'
        run: 
          python main.py #运行主程序
      - name: Record time  
        run: echo `date` > date.log

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-action"
          git add -A
          git commit -m "`date '+%Y-%m-%d %H:%M:%S'`"
          git status
          git push -f origin main
          git status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy:
    needs: rss-make
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
